from setuptools import setup, find_packages

setup(
    name="ring-attractor-rl",
    version="0.1.0",
    author="Anonymous",
    description="Spatial-Aware Decision-Making with Ring Attractors in Reinforcement Learning Systems",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    packages=find_packages(),
    install_requires=[
        "numpy==1.24.4",
        "gym==0.26.2",
        "atari-py",
        "gym-super-mario-bros==7.4.0",
        "ipython==8.12.3",
        "matplotlib",
        "matplotlib-inline",
        "nes_py==8.2.1",
        "networkx==3.1",
        "opencv-python",
        "pillow==10.4.0",
        "tensordict==0.3.0",
        "torch==2.2.0",
        "torchaudio==2.2.0",
        "torchrl==0.3.0",
        "torchvision==0.17.0",
        "tqdm",
        "mxnet",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Researchers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
)